export const mockData = [
  {
    id: "ffb90f25-e305-4eea-a305-6a670e6d9175",
    title: "Understanding Quantum Computing",
    author: "Alice Johnson",
    categories: "Technology, Science",
    tags: "Quantum, Computing, Future",
    comments: "12",
    datePublished: "2024-09-15",
    link: "https://www.google.com",
  },
  {
    id: "d14024da-2318-4c9c-a511-67c2a22074e6",
    title: "The Rise of AI",
    author: "Bob Smith",
    categories: "Technology, AI",
    tags: "AI, Machine Learning",
    comments: "25",
    datePublished: "2024-09-18",
    link: "https://www.youtube.com/",
  },
  {
    id: "3bd1aee6-9d46-436b-82a0-31a311441aa1",
    title: "Exploring the Universe",
    author: "Carol Davis",
    categories: "academics, Science",
    tags: "Space, Exploration",
    comments: "8",
    datePublished: "2024-09-20",
    link: "https://github.com/",
  },
  {
    id: "c0152066-06c9-4dde-84b1-f5b1ef440768",
    title: "Healthy Eating Habits",
    author: "David Wilson",
    categories: "growth, Lifestyle",
    tags: "Nutrition, Wellness",
    comments: "15",
    datePublished: "2024-09-12",
    link: "https://building-u.com/",
  },
  {
    id: "3b28abd8-aaec-45e1-a666-d01af6f7ec2c",
    title: "The Future of Renewable Energy",
    author: "Emma Brown",
    categories: "climate change, Energy",
    tags: "Renewable, Sustainability",
    comments: "5",
    datePublished: "2024-09-22",
    link: "https://www.instagram.com/",
  },
  {
    id: "3b28abd8-aaec-45e1-a666-d01af6f7ec26",
    title: "The Future of Renewable Energy",
    author: "Emma Brown",
    categories: "climate change, Energy",
    tags: "Renewable, Sustainability",
    comments: "5",
    datePublished: "2024-09-22",
    link: "https://www.instagram.com/",
  },
  {
    id: "3b28abd8-aaec-45e1-a666-d01af6f7ec25",
    title: "The Future of Renewable Energy",
    author: "Emma Brown",
    categories: "climate change, Energy",
    tags: "Renewable, Sustainability",
    comments: "5",
    datePublished: "2024-09-22",
    link: "https://www.instagram.com/",
  },
  {
    id: "3b28abd8-aaec-45e1-a666-d01af6f7ec29",
    title: "The Future of Renewable Energy",
    author: "Emma Brown",
    categories: "climate change, Energy",
    tags: "Renewable, Sustainability",
    comments: "5",
    datePublished: "2024-09-22",
    link: "https://www.instagram.com/",
  },
  {
    id: "3b28abd8-aaec-45e1-a666-d01af6f7ec23",
    title: "The Future of Renewable Energy",
    author: "Emma Brown",
    categories: "climate change, Energy",
    tags: "Renewable, Sustainability",
    comments: "5",
    datePublished: "2024-09-22",
    link: "https://www.instagram.com/",
  },
  {
    id: "3b28abd8-aaec-45e1-a666-d01af6f7ec22",
    title: "The Future of Renewable Energy",
    author: "Emma Brown",
    categories: "climate change, Energy",
    tags: "Renewable, Sustainability",
    comments: "5",
    datePublished: "2024-09-22",
    link: "https://www.instagram.com/",
  },
  {
    id: "3b28abd8-aaec-45e1-a666-d01af6f7ec21",
    title: "The Future of Renewable Energy",
    author: "Emma Brown",
    categories: "climate change, Energy",
    tags: "Renewable, Sustainability",
    comments: "5",
    datePublished: "2024-09-22",
    link: "https://www.instagram.com/",
  },
];